# Python 3.11 slimベースイメージを指定
FROM python:3.11-slim
# 必要なシステムパッケージをインストール
RUN apt-get update && apt-get install -y \
    gcc \
    libssl-dev \
    libffi-dev \
    libjpeg-dev \
    zlib1g-dev \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# 作業ディレクトリを指定
WORKDIR /app

# COPY pyproject.toml poetry.lock ./
COPY ./ ./

# Poetryのインストールと依存関係の設定
RUN pip install --no-cache-dir requests==2.32.3
RUN pip install --no-cache-dir Werkzeug==2.2.3
RUN pip install --no-cache-dir mysql-connector-python==8.0.31
RUN pip install --no-cache-dir Flask==2.2.2
    # pip install --no-cache-dir csv && \
    # pip install --no-cache-dir json && \
    # pip install --no-cache-dir os

# タイムゾーンを東京に設定
ENV TZ=Asia/Tokyo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

# プロキシ設定を解除
ENV http_proxy=""
ENV https_proxy=""

# コンテナが起動したときに実行されるプログラムを指定
CMD ["python3.11", python app.py"]
