

line_frontage
09:52:53	CREATE TABLE `line_frontage` (   `frontage_id` int NOT NULL,   `line_id` int NOT NULL,   `name` varchar(45) NOT NULL,   `cell_code` varchar(8) NOT NULL,   `car_model_id` int NOT NULL,   PRIMARY KEY (`frontage_id`),   KEY `line_idx` (`line_id`),   KEY `line_99_idx` (`line_id`),   CONSTRAINT `line_99` FOREIGN KEY (`line_id`) REFERENCES `line` (`line_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci	Error Code: 1142. REFERENCES command denied to user 'athena'@'10.104.16.87' for table 'line'	0.000 sec

line_inventory
09:53:38	CREATE TABLE `line_inventory` (   `inventory_id` int NOT NULL,   `frontage_id` int NOT NULL,   `part_number` varchar(20) NOT NULL,   `case_quantity` int NOT NULL,   `part_quantity` int NOT NULL,   `update_date` datetime NOT NULL,   PRIMARY KEY (`inventory_id`),   KEY `frontage_idx` (`frontage_id`),   KEY `part_idx` (`part_number`),   CONSTRAINT `frontage` FOREIGN KEY (`frontage_id`) REFERENCES `line_frontage` (`frontage_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci	Error Code: 1142. REFERENCES command denied to user 'athena'@'10.104.16.87' for table 'line_frontage'	0.000 sec

09:46:53	
production table
/*!50003 CREATE*/ /*!50017 DEFINER=`root`@`localhost`*/ /*!50003 TRIGGER `production_AFTER_INSERT` AFTER INSERT ON `production` FOR EACH ROW BEGIN  DECLARE id INT default 0; DECLARE total INT default 0; DECLARE case_total INT default 0; DECLARE done INT DEFAULT FALSE;  DECLARE cur_inventory CURSOR FOR  SELECT inventory_id,(part_quantity-quantity) as t,CEILING((part_quantity-quantity)/innner_parts) as c      FROM depal.futaba_product     inner join depal.line_product using(product_id)  inner join depal.line_frontage using(line_id)  inner join depal.line_inventory using(frontage_id)     inner join depal.composition using(product_id,part_number)     inner join depal.m_product using(part_number)     inner join depal.m_product_inventory using(part_number)  where product_id=new.product_id;      DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = TRUE;  OPEN cur_inventory;  loop1: LOOP      FETCH cur_inventory INTO  id,total,case_total;   IF done THEN       LEAVE loop1;     END IF;  UPDATE depal.line_inventory set case_quantity=case_total,part_quantity=total,update_date=new.time_stamp  WHERE depal.line_inventory.inventory_id=id;      END LOOP loop1;      CLOSE cur_inventory;  END */	Error Code: 1142. TRIGGER command denied to user 'athena'@'10.104.16.87' for table 'production'	0.062 sec

parts_supply table error
09:51:52	CREATE TABLE `parts_supply` (  `inventory_id` int NOT NULL,   `time_stamp` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,   `case_quantity` int NOT NULL,   PRIMARY KEY (`inventory_id`,`time_stamp`),   KEY `line_inventory_idx` (`inventory_id`),   CONSTRAINT `line_inventory` FOREIGN KEY (`inventory_id`) REFERENCES `line_inventory` (`inventory_id`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci	Error Code: 1142. REFERENCES command denied to user 'athena'@'10.104.16.87' for table 'line_inventory'	0.000 sec

